#!/bin/sh

echo "Checks Started"

# stash any unstaged changes
git stash -q --keep-index

# run the tests with the gradle wrapper
./gradlew test

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

if [ "$RESULT" != 0 ]
  then
    echo 1>&2 "Unit Tests Failed"
    exit 1
else
    echo "Unit tests all passed"
    exit 0
fi